name: Build GrabCut Image Segmentation Implementation (x86, x64, arm64)

on:
  pull_request:
    types: [synchronize, opened]
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022"]
        arch: ["x86", "x64", "arm64", "arm"]

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: lukka/get-cmake@latest

      - name: Download OpenCV [4.10.0] source code
        run: |
          git clone https://github.com/opencv/opencv.git
          cd opencv
          git checkout tags/4.10.0

      - name: Configure OpenCV with CMake for Static Library
        shell: pwsh
        run: |
          cd opencv
          mkdir build
          cd build

          # Choose the right CMake generator based on architecture
          if ("${{ matrix.arch }}" -eq 'x86') {
            $platform = "Win32"
          } elseif ("${{ matrix.arch }}" -eq 'x64') {
            $platform = "x64"
          } else {
            $platform = "ARM64"
          }

          cmake .. -G "Visual Studio 17 2022" -A $platform `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_SHARED_LIBS=OFF `
            -DCMAKE_INSTALL_PREFIX=D:/opencv-install `
            -DCMAKE_CXX_FLAGS="/DNDEBUG /D__ARM_NEON__=1" `
            -DENABLE_SSE=OFF `
            -DENABLE_SSE2=OFF `
            -DENABLE_AVX=OFF `
            -DENABLE_AVX2=OFF `
            -DWITH_ITT=OFF `
            -DWITH_OPENCL=OFF `
            -DWITH_DIRECTML=OFF `
            -DWITH_DIRECTX=OFF `
            -DWITH_ADE=OFF `
            -DWITH_CAROTENE=OFF
  
      - name: Build OpenCV Static Library
        shell: pwsh
        run: |
          cd opencv/build
          cmake --build . --config Release -- /p:Platform=${{ matrix.arch }}

      - name: Configure Project with CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          if ("${{ matrix.arch }}" -eq "x86") {
            cmake .. -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
              -DVCPKG_TARGET_TRIPLET=x86-windows-static `
              -DCMAKE_CXX_FLAGS="/DNDEBUG /D__SSE2__=0 /D__AVX__=0"
          } else {
            cmake .. -G "Visual Studio 17 2022" -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
              -DVCPKG_TARGET_TRIPLET=${{ matrix.arch }}-windows-static `
              -DCMAKE_CXX_FLAGS="/DNDEBUG /D__SSE2__=0 /D__AVX__=0"
          }

      - name: Build Project with CMake
        shell: pwsh
        run: |
          cd build
          cmake --build . --config Release -- /p:Platform=${{ matrix.arch }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grabcut-detection-${{ matrix.arch }}
          path: D:\a\grabcut_image_segementation\grabcut_image_segementation\build\bin\Release\

# DOCS :
# Add additional flags to the CMAKE_CXX_FLAGS variable to enable or disable specific features.
# https://stackoverflow.com/questions/13007926/opencv-grabcut-cpp-error

# Compilation on ARM64
# https://learn.arm.com/learning-paths/laptops-and-desktops/win-opencv/2-1-build-msvc/