name: Build GrabCut Image Segmentation Implementation (x86, x64, arm64)

on:
  pull_request:
    types: [synchronize, opened]
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019"]
        arch: ["x86", "x64", "arm64"]

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: lukka/get-cmake@latest
      
      - name: Install vcpkg packages
        run: |
          # Check if vcpkg is already installed
          if (Test-Path "C:/vcpkg") {
            Write-Host "vcpkg is already installed, applying patch..."

            # Apply patch to OpenCV to disable assertions
            cd C:/vcpkg
            git apply << 'EOF'
            --- ports/opencv4/portfile.cmake
            +++ ports/opencv4/portfile.cmake
            @@ -112,6 +112,8 @@
                 if(VCPKG_BUILD_TYPE STREQUAL "release")
                     set(CMAKE_CXX_FLAGS_RELEASE "/DNDEBUG ${CMAKE_CXX_FLAGS_RELEASE}")
                 endif()

            +    set(OPENCV_DISABLE_ASSERTS ON CACHE BOOL "Disable OpenCV asserts")
            +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DNDEBUG")
            EOF
          } else {
            Write-Host "vcpkg is not installed, skipping patch application."
          }

          # Install the necessary package
          C:/vcpkg/vcpkg install --triplet ${{ matrix.arch }}-windows-static


      - name: Configure Project with CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          if ("${{ matrix.arch }}" -eq "x86") {
            cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
              -DVCPKG_TARGET_TRIPLET=x86-windows-static `
              -DCMAKE_CXX_FLAGS="/DNDEBUG"
          } else {
            cmake .. -G "Visual Studio 16 2019" -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
              -DVCPKG_TARGET_TRIPLET=${{ matrix.arch }}-windows-static `
              -DCMAKE_CXX_FLAGS="/DNDEBUG"
          }
      
      - name: Build Project with CMake
        shell: pwsh
        run: |
          cd build
          cmake --build . --config Release -- /p:Platform=${{ matrix.arch }}
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grabcut-detection-${{ matrix.arch }}
          path: D:\a\grabcut_image_segementation\grabcut_image_segementation\build\bin\Release\

# DOCS :
# Add additional flags to the CMAKE_CXX_FLAGS variable to enable or disable specific features.
# https://stackoverflow.com/questions/13007926/opencv-grabcut-cpp-error