name: Build GrabCut Image Segmentation Implementation (x86, x64, arm64)

on:
  pull_request:
    types: [synchronize, opened]
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019"]
        arch: ["x86", "x64", "arm64"]

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: lukka/get-cmake@latest
      
      - name: Install OpenCV
        run: |
          choco install opencv -y
      
      - name: Build Project with CMake
        shell: pwsh
        run: |
          cd build
          cmake --build . --config Release -- /p:Platform=${{ matrix.arch }}
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grabcut-detection-${{ matrix.arch }}
          path: D:\a\grabcut_image_segementation\grabcut_image_segementation\build\bin\Release\

# DOCS :
# Add additional flags to the CMAKE_CXX_FLAGS variable to enable or disable specific features.
# https://stackoverflow.com/questions/13007926/opencv-grabcut-cpp-error
